# Generated by Django 3.2.8 on 2021-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.AddField(
            model_name='authuser',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
