# Generated by Django 3.2.8 on 2021-10-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211027_2001'),
        ('files', '0002_auto_20211027_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.uploaduser'),
        ),
    ]
