# Generated by Django 3.2.8 on 2021-10-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211027_2001'),
        ('task', '0006_auto_20211027_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='projectcolumn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.projectcolumns'),
            preserve_default=False,
        ),
    ]
