# Generated by Django 3.2.8 on 2021-10-30 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20211030_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 12, 2, 21, 895957)),
        ),
    ]
