# Generated by Django 3.2.8 on 2021-10-30 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ToDo', max_length=200)),
                ('code', models.CharField(default='TODO', max_length=200)),
            ],
            options={
                'db_table': 'task_columns',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='projectcolumn',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 12, 33, 8, 6386)),
        ),
        migrations.AddField(
            model_name='task',
            name='task_column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.taskcolumn'),
            preserve_default=False,
        ),
    ]
