# Generated by Django 3.2.8 on 2021-10-30 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20211030_1233'),
        ('task', '0012_auto_20211030_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 13, 4, 44, 703459)),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_column',
            field=models.ForeignKey(default='ToDo', on_delete=django.db.models.deletion.CASCADE, to='task.taskcolumn'),
        ),
    ]
