# Generated by Django 3.2.8 on 2021-10-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectmember'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectmember',
            table='project_member',
        ),
    ]
