# Generated by Django 3.2.8 on 2021-10-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_projectmember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcolumns',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.projectcolumns'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcolumns',
            name='code',
            field=models.CharField(default='TODO', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcolumns',
            name='name',
            field=models.CharField(default='ToDo', max_length=200),
        ),
    ]
