# Generated by Django 3.2.8 on 2021-10-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20211030_1233'),
        ('project', '0010_remove_project_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_column',
        ),
        migrations.DeleteModel(
            name='ProjectColumns',
        ),
    ]
