# Generated by Django 3.2.8 on 2021-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211027_2001'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=300)),
                ('content_type', models.CharField(max_length=100)),
                ('new_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=70, unique=True)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'upload_user',
            },
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
